@baseUrl = https://api.holedo.com/rest
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjM4MjksImV4cCI6MTk3MTI0Mzc1NH0.iD6C9KbsPNit4xmBEby-iighMVcrilS-xlsNcpUwdOM
@acceptHeader = application/vnd.github.v3.html+json

@getUsers = /users/get/?slug=hagen-rode-ee5&id=3829&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjM4MjksImV4cCI6MTk3MTI0Mzc1NH0.iD6C9KbsPNit4xmBEby-iighMVcrilS-xlsNcpUwdOM

# @updateUsers = /users/update/?slug=hagen-rode-ee5&id=3829
@updateUsers = /users/update/
@contentType = application/json




POST https://api.holedo.com/rest/users/update/
 ?apikey={{token}}
Authorization: Bearer {{token}}
Accept: {{contentType}}
Content-Type: {{contentType}}

{
    "id": 3829,
    "slug": "test",
    "banner": "https://res.cloudinary.com/dgj5m6kvt/image/upload/v1656756345/banners/pexels-pixabay-290595.jpg.jpg"
}


# If-None-Match: W/"2be29895933ee045023998cab0223520976c00c1c23e85bd6ca71706aa7c4cdd"

###

GET {{baseUrl}}/search/repositories
  ?q=flutter
  &page=1
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

###

GET {{baseUrl}}/repos/flutter/flutter/readme
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

###

PUT {{baseUrl}}/user/starred/ResoDev/foundations-stateful-widget
Authorization: bearer {{token}}
Content-Length: 0
Accept: {{acceptHeader}}

###

DELETE {{baseUrl}}/user/starred/ResoDev/foundations-stateful-widget
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

###

GET {{baseUrl}}/user/starred/ResoDev/foundations-stateful-widget
Authorization: bearer {{token}}
Accept: {{acceptHeader}}
