class Autogenerated {
  bool? success;
  dynamic errors;
  dynamic messages;
  Data? data;

  Autogenerated({this.success, this.errors, this.messages, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'] as bool;
    errors = json['errors'];
    messages = json['messages'];
    data = json['data'] != null
        ? new Data.fromJson(json['data'] as Map<String, dynamic>)
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['errors'] = this.errors;
    data['messages'] = this.messages;
    data['data'] = this.data!.toJson();
    return data;
  }
}

class Data {
  Settings? settings;
  Block? block;
  List<ArticleCategories>? articleCategories;

  Data({
    this.settings,
    this.block,
    this.articleCategories,
  });

  Data.fromJson(Map<String, dynamic> json) {
    settings = json['settings'] != null
        ? new Settings.fromJson(json['settings'] as Map<String, dynamic>)
        : null;

    block = json['Block'] != null
        ? new Block.fromJson(json['Block'] as Map<String, dynamic>)
        : null;
    if (json['ArticleCategories'] != null) {
      articleCategories = <ArticleCategories>[];
      json['ArticleCategories'].forEach((v) {
        articleCategories!
            .add(new ArticleCategories.fromJson(v as Map<String, dynamic>));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['settings'] = this.settings!.toJson();
    data['Block'] = this.block!.toJson();
    data['ArticleCategories'] =
        this.articleCategories!.map((v) => v.toJson()).toList();
    return data;
  }
}

class Settings {
  List<MembershipGrades>? membershipGrades;
  AchievementTypes? achievementTypes;
  Countries? countries;
  LanguagesTypes? languagesTypes;
  LanguagesProficiencies? languagesProficiencies;
  UserTitleTypes? userTitleTypes;
  ExpertiseList? expertiseList;

  Settings({
    this.membershipGrades,
    this.achievementTypes,
    this.countries,
    this.languagesTypes,
    this.languagesProficiencies,
    this.userTitleTypes,
    this.expertiseList,
  });

  Settings.fromJson(Map<String, dynamic> json) {
    if (json['membership_grades'] != null) {
      membershipGrades = <MembershipGrades>[];
      json['membership_grades'].forEach((v) {
        membershipGrades!
            .add(new MembershipGrades.fromJson(v as Map<String, dynamic>));
      });
    }
    achievementTypes = json['achievement_types'] != null
        ? new AchievementTypes.fromJson(
            json['achievement_types'] as Map<String, dynamic>)
        : null;
    countries = json['countries'] != null
        ? new Countries.fromJson(json['countries'] as Map<String, dynamic>)
        : null;
    languagesTypes = json['languages_types'] != null
        ? new LanguagesTypes.fromJson(
            json['languages_types'] as Map<String, dynamic>)
        : null;
    languagesProficiencies = json['languages_proficiencies'] != null
        ? new LanguagesProficiencies.fromJson(
            json['languages_proficiencies'] as Map<String, dynamic>)
        : null;
    userTitleTypes = json['user_title_types'] != null
        ? new UserTitleTypes.fromJson(
            json['user_title_types'] as Map<String, dynamic>)
        : null;
    expertiseList = json['expertise_list'] != null
        ? new ExpertiseList.fromJson(
            json['expertise_list'] as Map<String, dynamic>)
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['membership_grades'] =
        this.membershipGrades!.map((v) => v.toJson()).toList();
    data['achievement_types'] = this.achievementTypes!.toJson();
    data['countries'] = this.countries!.toJson();
    data['languages_types'] = this.languagesTypes!.toJson();
    data['languages_proficiencies'] = this.languagesProficiencies!.toJson();
    data['user_title_types'] = this.userTitleTypes!.toJson();
    data['expertise_list'] = this.expertiseList!.toJson();
    return data;
  }
}

class MembershipGrades {
  int? id;
  String? name;
  String? title;
  String? description;
  int? points;
  String? icon;

  MembershipGrades(
      {this.id,
      this.name,
      this.title,
      this.description,
      this.points,
      this.icon});

  MembershipGrades.fromJson(Map<String, dynamic> json) {
    id = json['id'] as int;
    name = json['name'] as String?;
    title = json['title'] as String?;
    description = json['description'] as String?;
    points = json['points'] as int?;
    icon = json['icon'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['title'] = this.title;
    data['description'] = this.description;
    data['points'] = this.points;
    data['icon'] = this.icon;
    return data;
  }
}

class AchievementTypes {
  String? s1;
  String? s2;
  String? s3;
  String? s4;
  String? s5;

  AchievementTypes({this.s1, this.s2, this.s3, this.s4, this.s5});

  AchievementTypes.fromJson(Map<String, dynamic> json) {
    s1 = json['1'] as String?;
    s2 = json['2'] as String?;
    s3 = json['3'] as String?;
    s4 = json['4'] as String?;
    s5 = json['5'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1'] = this.s1;
    data['2'] = this.s2;
    data['3'] = this.s3;
    data['4'] = this.s4;
    data['5'] = this.s5;
    return data;
  }
}

class Countries {
  String? s1;
  String? s2;
  String? s3;
  String? s4;
  String? s5;
  String? s6;
  String? s7;
  String? s8;
  String? s9;
  String? s10;
  String? s11;
  String? s12;
  String? s13;
  String? s14;
  String? s15;
  String? s16;
  String? s17;
  String? s18;
  String? s19;
  String? s20;
  String? s21;
  String? s22;
  String? s23;
  String? s24;
  String? s25;
  String? s26;
  String? s27;
  String? s28;
  String? s29;
  String? s30;
  String? s31;
  String? s32;
  String? s33;
  String? s34;
  String? s35;
  String? s36;
  String? s37;
  String? s38;
  String? s39;
  String? s40;
  String? s41;
  String? s42;
  String? s43;
  String? s44;
  String? s45;
  String? s46;
  String? s47;
  String? s48;
  String? s49;
  String? s50;
  String? s51;
  String? s52;
  String? s53;
  String? s54;
  String? s55;
  String? s56;
  String? s57;
  String? s58;
  String? s59;
  String? s60;
  String? s61;
  String? s62;
  String? s63;
  String? s64;
  String? s65;
  String? s66;
  String? s67;
  String? s68;
  String? s69;
  String? s70;
  String? s71;
  String? s72;
  String? s73;
  String? s74;
  String? s75;
  String? s76;
  String? s77;
  String? s78;
  String? s79;
  String? s80;
  String? s81;
  String? s82;
  String? s83;
  String? s84;
  String? s85;
  String? s86;
  String? s87;
  String? s88;
  String? s89;
  String? s90;
  String? s91;
  String? s92;
  String? s93;
  String? s94;
  String? s95;
  String? s96;
  String? s97;
  String? s98;
  String? s99;
  String? s100;
  String? s101;
  String? s102;
  String? s103;
  String? s104;
  String? s105;
  String? s106;
  String? s107;
  String? s108;
  String? s109;
  String? s110;
  String? s111;
  String? s112;
  String? s113;
  String? s114;
  String? s115;
  String? s116;
  String? s117;
  String? s118;
  String? s119;
  String? s120;
  String? s121;
  String? s122;
  String? s123;
  String? s124;
  String? s125;
  String? s126;
  String? s127;
  String? s128;
  String? s129;
  String? s130;
  String? s131;
  String? s132;
  String? s133;
  String? s134;
  String? s135;
  String? s136;
  String? s137;
  String? s138;
  String? s139;
  String? s140;
  String? s141;
  String? s142;
  String? s143;
  String? s144;
  String? s145;
  String? s146;
  String? s147;
  String? s148;
  String? s149;
  String? s150;
  String? s151;
  String? s152;
  String? s153;
  String? s154;
  String? s155;
  String? s156;
  String? s157;
  String? s158;
  String? s159;
  String? s160;
  String? s161;
  String? s162;
  String? s163;
  String? s164;
  String? s165;
  String? s166;
  String? s167;
  String? s168;
  String? s169;
  String? s170;
  String? s171;
  String? s172;
  String? s173;
  String? s174;
  String? s175;
  String? s176;
  String? s177;
  String? s178;
  String? s179;
  String? s180;
  String? s181;
  String? s182;
  String? s183;
  String? s184;
  String? s185;
  String? s186;
  String? s187;
  String? s188;
  String? s189;
  String? s190;
  String? s191;
  String? s192;
  String? s193;
  String? s194;
  String? s195;
  String? s196;
  String? s197;
  String? s198;
  String? s199;
  String? s200;
  String? s201;
  String? s202;
  String? s203;
  String? s204;
  String? s205;
  String? s206;
  String? s207;
  String? s208;
  String? s209;
  String? s210;
  String? s211;
  String? s212;
  String? s213;
  String? s214;
  String? s215;
  String? s216;
  String? s217;
  String? s218;
  String? s219;
  String? s220;
  String? s221;
  String? s222;
  String? s223;
  String? s224;
  String? s225;
  String? s226;
  String? s227;
  String? s228;
  String? s229;
  String? s230;
  String? s231;
  String? s232;
  String? s233;
  String? s234;
  String? s235;
  String? s236;
  String? s237;
  String? s238;
  String? s239;
  String? s240;
  String? s241;
  String? s242;
  String? s243;
  String? s244;
  String? s245;
  String? s246;
  String? s247;
  String? s248;

  Countries(
      {this.s1,
      this.s2,
      this.s3,
      this.s4,
      this.s5,
      this.s6,
      this.s7,
      this.s8,
      this.s9,
      this.s10,
      this.s11,
      this.s12,
      this.s13,
      this.s14,
      this.s15,
      this.s16,
      this.s17,
      this.s18,
      this.s19,
      this.s20,
      this.s21,
      this.s22,
      this.s23,
      this.s24,
      this.s25,
      this.s26,
      this.s27,
      this.s28,
      this.s29,
      this.s30,
      this.s31,
      this.s32,
      this.s33,
      this.s34,
      this.s35,
      this.s36,
      this.s37,
      this.s38,
      this.s39,
      this.s40,
      this.s41,
      this.s42,
      this.s43,
      this.s44,
      this.s45,
      this.s46,
      this.s47,
      this.s48,
      this.s49,
      this.s50,
      this.s51,
      this.s52,
      this.s53,
      this.s54,
      this.s55,
      this.s56,
      this.s57,
      this.s58,
      this.s59,
      this.s60,
      this.s61,
      this.s62,
      this.s63,
      this.s64,
      this.s65,
      this.s66,
      this.s67,
      this.s68,
      this.s69,
      this.s70,
      this.s71,
      this.s72,
      this.s73,
      this.s74,
      this.s75,
      this.s76,
      this.s77,
      this.s78,
      this.s79,
      this.s80,
      this.s81,
      this.s82,
      this.s83,
      this.s84,
      this.s85,
      this.s86,
      this.s87,
      this.s88,
      this.s89,
      this.s90,
      this.s91,
      this.s92,
      this.s93,
      this.s94,
      this.s95,
      this.s96,
      this.s97,
      this.s98,
      this.s99,
      this.s100,
      this.s101,
      this.s102,
      this.s103,
      this.s104,
      this.s105,
      this.s106,
      this.s107,
      this.s108,
      this.s109,
      this.s110,
      this.s111,
      this.s112,
      this.s113,
      this.s114,
      this.s115,
      this.s116,
      this.s117,
      this.s118,
      this.s119,
      this.s120,
      this.s121,
      this.s122,
      this.s123,
      this.s124,
      this.s125,
      this.s126,
      this.s127,
      this.s128,
      this.s129,
      this.s130,
      this.s131,
      this.s132,
      this.s133,
      this.s134,
      this.s135,
      this.s136,
      this.s137,
      this.s138,
      this.s139,
      this.s140,
      this.s141,
      this.s142,
      this.s143,
      this.s144,
      this.s145,
      this.s146,
      this.s147,
      this.s148,
      this.s149,
      this.s150,
      this.s151,
      this.s152,
      this.s153,
      this.s154,
      this.s155,
      this.s156,
      this.s157,
      this.s158,
      this.s159,
      this.s160,
      this.s161,
      this.s162,
      this.s163,
      this.s164,
      this.s165,
      this.s166,
      this.s167,
      this.s168,
      this.s169,
      this.s170,
      this.s171,
      this.s172,
      this.s173,
      this.s174,
      this.s175,
      this.s176,
      this.s177,
      this.s178,
      this.s179,
      this.s180,
      this.s181,
      this.s182,
      this.s183,
      this.s184,
      this.s185,
      this.s186,
      this.s187,
      this.s188,
      this.s189,
      this.s190,
      this.s191,
      this.s192,
      this.s193,
      this.s194,
      this.s195,
      this.s196,
      this.s197,
      this.s198,
      this.s199,
      this.s200,
      this.s201,
      this.s202,
      this.s203,
      this.s204,
      this.s205,
      this.s206,
      this.s207,
      this.s208,
      this.s209,
      this.s210,
      this.s211,
      this.s212,
      this.s213,
      this.s214,
      this.s215,
      this.s216,
      this.s217,
      this.s218,
      this.s219,
      this.s220,
      this.s221,
      this.s222,
      this.s223,
      this.s224,
      this.s225,
      this.s226,
      this.s227,
      this.s228,
      this.s229,
      this.s230,
      this.s231,
      this.s232,
      this.s233,
      this.s234,
      this.s235,
      this.s236,
      this.s237,
      this.s238,
      this.s239,
      this.s240,
      this.s241,
      this.s242,
      this.s243,
      this.s244,
      this.s245,
      this.s246,
      this.s247,
      this.s248});

  Countries.fromJson(Map<String, dynamic> json) {
    s1 = json['1'] as String?;
    s2 = json['2'] as String?;
    s3 = json['3'] as String?;
    s4 = json['4'] as String?;
    s5 = json['5'] as String?;
    s6 = json['6'] as String?;
    s7 = json['7'] as String?;
    s8 = json['8'] as String?;
    s9 = json['9'] as String?;
    s10 = json['10'] as String?;
    s11 = json['11'] as String?;
    s12 = json['12'] as String?;
    s13 = json['13'] as String?;
    s14 = json['14'] as String?;
    s15 = json['15'] as String?;
    s16 = json['16'] as String?;
    s17 = json['17'] as String?;
    s18 = json['18'] as String?;
    s19 = json['19'] as String?;
    s20 = json['20'] as String?;
    s21 = json['21'] as String?;
    s22 = json['22'] as String?;
    s23 = json['23'] as String?;
    s24 = json['24'] as String?;
    s25 = json['25'] as String?;
    s26 = json['26'] as String?;
    s27 = json['27'] as String?;
    s28 = json['28'] as String?;
    s29 = json['29'] as String?;
    s30 = json['30'] as String?;
    s31 = json['31'] as String?;
    s32 = json['32'] as String?;
    s33 = json['33'] as String?;
    s34 = json['34'] as String?;
    s35 = json['35'] as String?;
    s36 = json['36'] as String?;
    s37 = json['37'] as String?;
    s38 = json['38'] as String?;
    s39 = json['39'] as String?;
    s40 = json['40'] as String?;
    s41 = json['41'] as String?;
    s42 = json['42'] as String?;
    s43 = json['43'] as String?;
    s44 = json['44'] as String?;
    s45 = json['45'] as String?;
    s46 = json['46'] as String?;
    s47 = json['47'] as String?;
    s48 = json['48'] as String?;
    s49 = json['49'] as String?;
    s50 = json['50'] as String?;
    s51 = json['51'] as String?;
    s52 = json['52'] as String?;
    s53 = json['53'] as String?;
    s54 = json['54'] as String?;
    s55 = json['55'] as String?;
    s56 = json['56'] as String?;
    s57 = json['57'] as String?;
    s58 = json['58'] as String?;
    s59 = json['59'] as String?;
    s60 = json['60'] as String?;
    s61 = json['61'] as String?;
    s62 = json['62'] as String?;
    s63 = json['63'] as String?;
    s64 = json['64'] as String?;
    s65 = json['65'] as String?;
    s66 = json['66'] as String?;
    s67 = json['67'] as String?;
    s68 = json['68'] as String?;
    s69 = json['69'] as String?;
    s70 = json['70'] as String?;
    s71 = json['71'] as String?;
    s72 = json['72'] as String?;
    s73 = json['73'] as String?;
    s74 = json['74'] as String?;
    s75 = json['75'] as String?;
    s76 = json['76'] as String?;
    s77 = json['77'] as String?;
    s78 = json['78'] as String?;
    s79 = json['79'] as String?;
    s80 = json['80'] as String?;
    s81 = json['81'] as String?;
    s82 = json['82'] as String?;
    s83 = json['83'] as String?;
    s84 = json['84'] as String?;
    s85 = json['85'] as String?;
    s86 = json['86'] as String?;
    s87 = json['87'] as String?;
    s88 = json['88'] as String?;
    s89 = json['89'] as String?;
    s90 = json['90'] as String?;
    s91 = json['91'] as String?;
    s92 = json['92'] as String?;
    s93 = json['93'] as String?;
    s94 = json['94'] as String?;
    s95 = json['95'] as String?;
    s96 = json['96'] as String?;
    s97 = json['97'] as String?;
    s98 = json['98'] as String?;
    s99 = json['99'] as String?;
    s100 = json['100'] as String?;
    s101 = json['101'] as String?;
    s102 = json['102'] as String?;
    s103 = json['103'] as String?;
    s104 = json['104'] as String?;
    s105 = json['105'] as String?;
    s106 = json['106'] as String?;
    s107 = json['107'] as String?;
    s108 = json['108'] as String?;
    s109 = json['109'] as String?;
    s110 = json['110'] as String?;
    s111 = json['111'] as String?;
    s112 = json['112'] as String?;
    s113 = json['113'] as String?;
    s114 = json['114'] as String?;
    s115 = json['115'] as String?;
    s116 = json['116'] as String?;
    s117 = json['117'] as String?;
    s118 = json['118'] as String?;
    s119 = json['119'] as String?;
    s120 = json['120'] as String?;
    s121 = json['121'] as String?;
    s122 = json['122'] as String?;
    s123 = json['123'] as String?;
    s124 = json['124'] as String?;
    s125 = json['125'] as String?;
    s126 = json['126'] as String?;
    s127 = json['127'] as String?;
    s128 = json['128'] as String?;
    s129 = json['129'] as String?;
    s130 = json['130'] as String?;
    s131 = json['131'] as String?;
    s132 = json['132'] as String?;
    s133 = json['133'] as String?;
    s134 = json['134'] as String?;
    s135 = json['135'] as String?;
    s136 = json['136'] as String?;
    s137 = json['137'] as String?;
    s138 = json['138'] as String?;
    s139 = json['139'] as String?;
    s140 = json['140'] as String?;
    s141 = json['141'] as String?;
    s142 = json['142'] as String?;
    s143 = json['143'] as String?;
    s144 = json['144'] as String?;
    s145 = json['145'] as String?;
    s146 = json['146'] as String?;
    s147 = json['147'] as String?;
    s148 = json['148'] as String?;
    s149 = json['149'] as String?;
    s150 = json['150'] as String?;
    s151 = json['151'] as String?;
    s152 = json['152'] as String?;
    s153 = json['153'] as String?;
    s154 = json['154'] as String?;
    s155 = json['155'] as String?;
    s156 = json['156'] as String?;
    s157 = json['157'] as String?;
    s158 = json['158'] as String?;
    s159 = json['159'] as String?;
    s160 = json['160'] as String?;
    s161 = json['161'] as String?;
    s162 = json['162'] as String?;
    s163 = json['163'] as String?;
    s164 = json['164'] as String?;
    s165 = json['165'] as String?;
    s166 = json['166'] as String?;
    s167 = json['167'] as String?;
    s168 = json['168'] as String?;
    s169 = json['169'] as String?;
    s170 = json['170'] as String?;
    s171 = json['171'] as String?;
    s172 = json['172'] as String?;
    s173 = json['173'] as String?;
    s174 = json['174'] as String?;
    s175 = json['175'] as String?;
    s176 = json['176'] as String?;
    s177 = json['177'] as String?;
    s178 = json['178'] as String?;
    s179 = json['179'] as String?;
    s180 = json['180'] as String?;
    s181 = json['181'] as String?;
    s182 = json['182'] as String?;
    s183 = json['183'] as String?;
    s184 = json['184'] as String?;
    s185 = json['185'] as String?;
    s186 = json['186'] as String?;
    s187 = json['187'] as String?;
    s188 = json['188'] as String?;
    s189 = json['189'] as String?;
    s190 = json['190'] as String?;
    s191 = json['191'] as String?;
    s192 = json['192'] as String?;
    s193 = json['193'] as String?;
    s194 = json['194'] as String?;
    s195 = json['195'] as String?;
    s196 = json['196'] as String?;
    s197 = json['197'] as String?;
    s198 = json['198'] as String?;
    s199 = json['199'] as String?;
    s200 = json['200'] as String?;
    s201 = json['201'] as String?;
    s202 = json['202'] as String?;
    s203 = json['203'] as String?;
    s204 = json['204'] as String?;
    s205 = json['205'] as String?;
    s206 = json['206'] as String?;
    s207 = json['207'] as String?;
    s208 = json['208'] as String?;
    s209 = json['209'] as String?;
    s210 = json['210'] as String?;
    s211 = json['211'] as String?;
    s212 = json['212'] as String?;
    s213 = json['213'] as String?;
    s214 = json['214'] as String?;
    s215 = json['215'] as String?;
    s216 = json['216'] as String?;
    s217 = json['217'] as String?;
    s218 = json['218'] as String?;
    s219 = json['219'] as String?;
    s220 = json['220'] as String?;
    s221 = json['221'] as String?;
    s222 = json['222'] as String?;
    s223 = json['223'] as String?;
    s224 = json['224'] as String?;
    s225 = json['225'] as String?;
    s226 = json['226'] as String?;
    s227 = json['227'] as String?;
    s228 = json['228'] as String?;
    s229 = json['229'] as String?;
    s230 = json['230'] as String?;
    s231 = json['231'] as String?;
    s232 = json['232'] as String?;
    s233 = json['233'] as String?;
    s234 = json['234'] as String?;
    s235 = json['235'] as String?;
    s236 = json['236'] as String?;
    s237 = json['237'] as String?;
    s238 = json['238'] as String?;
    s239 = json['239'] as String?;
    s240 = json['240'] as String?;
    s241 = json['241'] as String?;
    s242 = json['242'] as String?;
    s243 = json['243'] as String?;
    s244 = json['244'] as String?;
    s245 = json['245'] as String?;
    s246 = json['246'] as String?;
    s247 = json['247'] as String?;
    s248 = json['248'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1'] = this.s1;
    data['2'] = this.s2;
    data['3'] = this.s3;
    data['4'] = this.s4;
    data['5'] = this.s5;
    data['6'] = this.s6;
    data['7'] = this.s7;
    data['8'] = this.s8;
    data['9'] = this.s9;
    data['10'] = this.s10;
    data['11'] = this.s11;
    data['12'] = this.s12;
    data['13'] = this.s13;
    data['14'] = this.s14;
    data['15'] = this.s15;
    data['16'] = this.s16;
    data['17'] = this.s17;
    data['18'] = this.s18;
    data['19'] = this.s19;
    data['20'] = this.s20;
    data['21'] = this.s21;
    data['22'] = this.s22;
    data['23'] = this.s23;
    data['24'] = this.s24;
    data['25'] = this.s25;
    data['26'] = this.s26;
    data['27'] = this.s27;
    data['28'] = this.s28;
    data['29'] = this.s29;
    data['30'] = this.s30;
    data['31'] = this.s31;
    data['32'] = this.s32;
    data['33'] = this.s33;
    data['34'] = this.s34;
    data['35'] = this.s35;
    data['36'] = this.s36;
    data['37'] = this.s37;
    data['38'] = this.s38;
    data['39'] = this.s39;
    data['40'] = this.s40;
    data['41'] = this.s41;
    data['42'] = this.s42;
    data['43'] = this.s43;
    data['44'] = this.s44;
    data['45'] = this.s45;
    data['46'] = this.s46;
    data['47'] = this.s47;
    data['48'] = this.s48;
    data['49'] = this.s49;
    data['50'] = this.s50;
    data['51'] = this.s51;
    data['52'] = this.s52;
    data['53'] = this.s53;
    data['54'] = this.s54;
    data['55'] = this.s55;
    data['56'] = this.s56;
    data['57'] = this.s57;
    data['58'] = this.s58;
    data['59'] = this.s59;
    data['60'] = this.s60;
    data['61'] = this.s61;
    data['62'] = this.s62;
    data['63'] = this.s63;
    data['64'] = this.s64;
    data['65'] = this.s65;
    data['66'] = this.s66;
    data['67'] = this.s67;
    data['68'] = this.s68;
    data['69'] = this.s69;
    data['70'] = this.s70;
    data['71'] = this.s71;
    data['72'] = this.s72;
    data['73'] = this.s73;
    data['74'] = this.s74;
    data['75'] = this.s75;
    data['76'] = this.s76;
    data['77'] = this.s77;
    data['78'] = this.s78;
    data['79'] = this.s79;
    data['80'] = this.s80;
    data['81'] = this.s81;
    data['82'] = this.s82;
    data['83'] = this.s83;
    data['84'] = this.s84;
    data['85'] = this.s85;
    data['86'] = this.s86;
    data['87'] = this.s87;
    data['88'] = this.s88;
    data['89'] = this.s89;
    data['90'] = this.s90;
    data['91'] = this.s91;
    data['92'] = this.s92;
    data['93'] = this.s93;
    data['94'] = this.s94;
    data['95'] = this.s95;
    data['96'] = this.s96;
    data['97'] = this.s97;
    data['98'] = this.s98;
    data['99'] = this.s99;
    data['100'] = this.s100;
    data['101'] = this.s101;
    data['102'] = this.s102;
    data['103'] = this.s103;
    data['104'] = this.s104;
    data['105'] = this.s105;
    data['106'] = this.s106;
    data['107'] = this.s107;
    data['108'] = this.s108;
    data['109'] = this.s109;
    data['110'] = this.s110;
    data['111'] = this.s111;
    data['112'] = this.s112;
    data['113'] = this.s113;
    data['114'] = this.s114;
    data['115'] = this.s115;
    data['116'] = this.s116;
    data['117'] = this.s117;
    data['118'] = this.s118;
    data['119'] = this.s119;
    data['120'] = this.s120;
    data['121'] = this.s121;
    data['122'] = this.s122;
    data['123'] = this.s123;
    data['124'] = this.s124;
    data['125'] = this.s125;
    data['126'] = this.s126;
    data['127'] = this.s127;
    data['128'] = this.s128;
    data['129'] = this.s129;
    data['130'] = this.s130;
    data['131'] = this.s131;
    data['132'] = this.s132;
    data['133'] = this.s133;
    data['134'] = this.s134;
    data['135'] = this.s135;
    data['136'] = this.s136;
    data['137'] = this.s137;
    data['138'] = this.s138;
    data['139'] = this.s139;
    data['140'] = this.s140;
    data['141'] = this.s141;
    data['142'] = this.s142;
    data['143'] = this.s143;
    data['144'] = this.s144;
    data['145'] = this.s145;
    data['146'] = this.s146;
    data['147'] = this.s147;
    data['148'] = this.s148;
    data['149'] = this.s149;
    data['150'] = this.s150;
    data['151'] = this.s151;
    data['152'] = this.s152;
    data['153'] = this.s153;
    data['154'] = this.s154;
    data['155'] = this.s155;
    data['156'] = this.s156;
    data['157'] = this.s157;
    data['158'] = this.s158;
    data['159'] = this.s159;
    data['160'] = this.s160;
    data['161'] = this.s161;
    data['162'] = this.s162;
    data['163'] = this.s163;
    data['164'] = this.s164;
    data['165'] = this.s165;
    data['166'] = this.s166;
    data['167'] = this.s167;
    data['168'] = this.s168;
    data['169'] = this.s169;
    data['170'] = this.s170;
    data['171'] = this.s171;
    data['172'] = this.s172;
    data['173'] = this.s173;
    data['174'] = this.s174;
    data['175'] = this.s175;
    data['176'] = this.s176;
    data['177'] = this.s177;
    data['178'] = this.s178;
    data['179'] = this.s179;
    data['180'] = this.s180;
    data['181'] = this.s181;
    data['182'] = this.s182;
    data['183'] = this.s183;
    data['184'] = this.s184;
    data['185'] = this.s185;
    data['186'] = this.s186;
    data['187'] = this.s187;
    data['188'] = this.s188;
    data['189'] = this.s189;
    data['190'] = this.s190;
    data['191'] = this.s191;
    data['192'] = this.s192;
    data['193'] = this.s193;
    data['194'] = this.s194;
    data['195'] = this.s195;
    data['196'] = this.s196;
    data['197'] = this.s197;
    data['198'] = this.s198;
    data['199'] = this.s199;
    data['200'] = this.s200;
    data['201'] = this.s201;
    data['202'] = this.s202;
    data['203'] = this.s203;
    data['204'] = this.s204;
    data['205'] = this.s205;
    data['206'] = this.s206;
    data['207'] = this.s207;
    data['208'] = this.s208;
    data['209'] = this.s209;
    data['210'] = this.s210;
    data['211'] = this.s211;
    data['212'] = this.s212;
    data['213'] = this.s213;
    data['214'] = this.s214;
    data['215'] = this.s215;
    data['216'] = this.s216;
    data['217'] = this.s217;
    data['218'] = this.s218;
    data['219'] = this.s219;
    data['220'] = this.s220;
    data['221'] = this.s221;
    data['222'] = this.s222;
    data['223'] = this.s223;
    data['224'] = this.s224;
    data['225'] = this.s225;
    data['226'] = this.s226;
    data['227'] = this.s227;
    data['228'] = this.s228;
    data['229'] = this.s229;
    data['230'] = this.s230;
    data['231'] = this.s231;
    data['232'] = this.s232;
    data['233'] = this.s233;
    data['234'] = this.s234;
    data['235'] = this.s235;
    data['236'] = this.s236;
    data['237'] = this.s237;
    data['238'] = this.s238;
    data['239'] = this.s239;
    data['240'] = this.s240;
    data['241'] = this.s241;
    data['242'] = this.s242;
    data['243'] = this.s243;
    data['244'] = this.s244;
    data['245'] = this.s245;
    data['246'] = this.s246;
    data['247'] = this.s247;
    data['248'] = this.s248;
    return data;
  }
}

class LanguagesTypes {
  String? s1;
  String? s2;
  String? s3;
  String? s4;
  String? s5;
  String? s6;
  String? s7;
  String? s8;
  String? s9;
  String? s10;
  String? s11;
  String? s12;
  String? s13;
  String? s14;
  String? s15;
  String? s16;
  String? s17;
  String? s18;
  String? s19;
  String? s20;
  String? s21;
  String? s22;
  String? s23;
  String? s24;
  String? s25;
  String? s26;
  String? s27;
  String? s28;
  String? s29;
  String? s30;
  String? s31;
  String? s32;
  String? s33;
  String? s34;
  String? s35;
  String? s36;
  String? s37;
  String? s38;
  String? s39;
  String? s40;
  String? s41;
  String? s42;
  String? s43;
  String? s44;
  String? s45;
  String? s46;
  String? s47;
  String? s48;
  String? s49;
  String? s50;
  String? s51;
  String? s52;
  String? s53;
  String? s54;
  String? s55;
  String? s56;
  String? s57;
  String? s58;
  String? s59;
  String? s60;
  String? s61;
  String? s62;
  String? s63;
  String? s64;
  String? s65;
  String? s66;
  String? s67;
  String? s68;
  String? s69;
  String? s70;
  String? s71;
  String? s72;
  String? s73;
  String? s74;
  String? s75;
  String? s76;
  String? s77;
  String? s78;
  String? s79;
  String? s80;
  String? s81;
  String? s82;
  String? s83;
  String? s84;
  String? s85;
  String? s86;
  String? s87;
  String? s88;
  String? s89;
  String? s90;
  String? s91;
  String? s92;
  String? s93;
  String? s94;
  String? s95;
  String? s96;
  String? s97;
  String? s98;
  String? s99;
  String? s100;
  String? s101;
  String? s102;
  String? s103;
  String? s104;
  String? s105;
  String? s106;
  String? s107;
  String? s108;
  String? s109;
  String? s110;
  String? s111;
  String? s112;
  String? s113;
  String? s114;
  String? s115;
  String? s116;
  String? s117;
  String? s118;
  String? s119;
  String? s120;
  String? s121;
  String? s122;
  String? s123;
  String? s124;
  String? s125;
  String? s126;
  String? s127;
  String? s128;
  String? s129;
  String? s130;
  String? s131;
  String? s132;
  String? s133;
  String? s134;
  String? s135;

  LanguagesTypes(
      {this.s1,
      this.s2,
      this.s3,
      this.s4,
      this.s5,
      this.s6,
      this.s7,
      this.s8,
      this.s9,
      this.s10,
      this.s11,
      this.s12,
      this.s13,
      this.s14,
      this.s15,
      this.s16,
      this.s17,
      this.s18,
      this.s19,
      this.s20,
      this.s21,
      this.s22,
      this.s23,
      this.s24,
      this.s25,
      this.s26,
      this.s27,
      this.s28,
      this.s29,
      this.s30,
      this.s31,
      this.s32,
      this.s33,
      this.s34,
      this.s35,
      this.s36,
      this.s37,
      this.s38,
      this.s39,
      this.s40,
      this.s41,
      this.s42,
      this.s43,
      this.s44,
      this.s45,
      this.s46,
      this.s47,
      this.s48,
      this.s49,
      this.s50,
      this.s51,
      this.s52,
      this.s53,
      this.s54,
      this.s55,
      this.s56,
      this.s57,
      this.s58,
      this.s59,
      this.s60,
      this.s61,
      this.s62,
      this.s63,
      this.s64,
      this.s65,
      this.s66,
      this.s67,
      this.s68,
      this.s69,
      this.s70,
      this.s71,
      this.s72,
      this.s73,
      this.s74,
      this.s75,
      this.s76,
      this.s77,
      this.s78,
      this.s79,
      this.s80,
      this.s81,
      this.s82,
      this.s83,
      this.s84,
      this.s85,
      this.s86,
      this.s87,
      this.s88,
      this.s89,
      this.s90,
      this.s91,
      this.s92,
      this.s93,
      this.s94,
      this.s95,
      this.s96,
      this.s97,
      this.s98,
      this.s99,
      this.s100,
      this.s101,
      this.s102,
      this.s103,
      this.s104,
      this.s105,
      this.s106,
      this.s107,
      this.s108,
      this.s109,
      this.s110,
      this.s111,
      this.s112,
      this.s113,
      this.s114,
      this.s115,
      this.s116,
      this.s117,
      this.s118,
      this.s119,
      this.s120,
      this.s121,
      this.s122,
      this.s123,
      this.s124,
      this.s125,
      this.s126,
      this.s127,
      this.s128,
      this.s129,
      this.s130,
      this.s131,
      this.s132,
      this.s133,
      this.s134,
      this.s135});

  LanguagesTypes.fromJson(Map<String, dynamic> json) {
    s1 = json['1'] as String?;
    s2 = json['2'] as String?;
    s3 = json['3'] as String?;
    s4 = json['4'] as String?;
    s5 = json['5'] as String?;
    s6 = json['6'] as String?;
    s7 = json['7'] as String?;
    s8 = json['8'] as String?;
    s9 = json['9'] as String?;
    s10 = json['10'] as String?;
    s11 = json['11'] as String?;
    s12 = json['12'] as String?;
    s13 = json['13'] as String?;
    s14 = json['14'] as String?;
    s15 = json['15'] as String?;
    s16 = json['16'] as String?;
    s17 = json['17'] as String?;
    s18 = json['18'] as String?;
    s19 = json['19'] as String?;
    s20 = json['20'] as String?;
    s21 = json['21'] as String?;
    s22 = json['22'] as String?;
    s23 = json['23'] as String?;
    s24 = json['24'] as String?;
    s25 = json['25'] as String?;
    s26 = json['26'] as String?;
    s27 = json['27'] as String?;
    s28 = json['28'] as String?;
    s29 = json['29'] as String?;
    s30 = json['30'] as String?;
    s31 = json['31'] as String?;
    s32 = json['32'] as String?;
    s33 = json['33'] as String?;
    s34 = json['34'] as String?;
    s35 = json['35'] as String?;
    s36 = json['36'] as String?;
    s37 = json['37'] as String?;
    s38 = json['38'] as String?;
    s39 = json['39'] as String?;
    s40 = json['40'] as String?;
    s41 = json['41'] as String?;
    s42 = json['42'] as String?;
    s43 = json['43'] as String?;
    s44 = json['44'] as String?;
    s45 = json['45'] as String?;
    s46 = json['46'] as String?;
    s47 = json['47'] as String?;
    s48 = json['48'] as String?;
    s49 = json['49'] as String?;
    s50 = json['50'] as String?;
    s51 = json['51'] as String?;
    s52 = json['52'] as String?;
    s53 = json['53'] as String?;
    s54 = json['54'] as String?;
    s55 = json['55'] as String?;
    s56 = json['56'] as String?;
    s57 = json['57'] as String?;
    s58 = json['58'] as String?;
    s59 = json['59'] as String?;
    s60 = json['60'] as String?;
    s61 = json['61'] as String?;
    s62 = json['62'] as String?;
    s63 = json['63'] as String?;
    s64 = json['64'] as String?;
    s65 = json['65'] as String?;
    s66 = json['66'] as String?;
    s67 = json['67'] as String?;
    s68 = json['68'] as String?;
    s69 = json['69'] as String?;
    s70 = json['70'] as String?;
    s71 = json['71'] as String?;
    s72 = json['72'] as String?;
    s73 = json['73'] as String?;
    s74 = json['74'] as String?;
    s75 = json['75'] as String?;
    s76 = json['76'] as String?;
    s77 = json['77'] as String?;
    s78 = json['78'] as String?;
    s79 = json['79'] as String?;
    s80 = json['80'] as String?;
    s81 = json['81'] as String?;
    s82 = json['82'] as String?;
    s83 = json['83'] as String?;
    s84 = json['84'] as String?;
    s85 = json['85'] as String?;
    s86 = json['86'] as String?;
    s87 = json['87'] as String?;
    s88 = json['88'] as String?;
    s89 = json['89'] as String?;
    s90 = json['90'] as String?;
    s91 = json['91'] as String?;
    s92 = json['92'] as String?;
    s93 = json['93'] as String?;
    s94 = json['94'] as String?;
    s95 = json['95'] as String?;
    s96 = json['96'] as String?;
    s97 = json['97'] as String?;
    s98 = json['98'] as String?;
    s99 = json['99'] as String?;
    s100 = json['100'] as String?;
    s101 = json['101'] as String?;
    s102 = json['102'] as String?;
    s103 = json['103'] as String?;
    s104 = json['104'] as String?;
    s105 = json['105'] as String?;
    s106 = json['106'] as String?;
    s107 = json['107'] as String?;
    s108 = json['108'] as String?;
    s109 = json['109'] as String?;
    s110 = json['110'] as String?;
    s111 = json['111'] as String?;
    s112 = json['112'] as String?;
    s113 = json['113'] as String?;
    s114 = json['114'] as String?;
    s115 = json['115'] as String?;
    s116 = json['116'] as String?;
    s117 = json['117'] as String?;
    s118 = json['118'] as String?;
    s119 = json['119'] as String?;
    s120 = json['120'] as String?;
    s121 = json['121'] as String?;
    s122 = json['122'] as String?;
    s123 = json['123'] as String?;
    s124 = json['124'] as String?;
    s125 = json['125'] as String?;
    s126 = json['126'] as String?;
    s127 = json['127'] as String?;
    s128 = json['128'] as String?;
    s129 = json['129'] as String?;
    s130 = json['130'] as String?;
    s131 = json['131'] as String?;
    s132 = json['132'] as String?;
    s133 = json['133'] as String?;
    s134 = json['134'] as String?;
    s135 = json['135'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1'] = this.s1;
    data['2'] = this.s2;
    data['3'] = this.s3;
    data['4'] = this.s4;
    data['5'] = this.s5;
    data['6'] = this.s6;
    data['7'] = this.s7;
    data['8'] = this.s8;
    data['9'] = this.s9;
    data['10'] = this.s10;
    data['11'] = this.s11;
    data['12'] = this.s12;
    data['13'] = this.s13;
    data['14'] = this.s14;
    data['15'] = this.s15;
    data['16'] = this.s16;
    data['17'] = this.s17;
    data['18'] = this.s18;
    data['19'] = this.s19;
    data['20'] = this.s20;
    data['21'] = this.s21;
    data['22'] = this.s22;
    data['23'] = this.s23;
    data['24'] = this.s24;
    data['25'] = this.s25;
    data['26'] = this.s26;
    data['27'] = this.s27;
    data['28'] = this.s28;
    data['29'] = this.s29;
    data['30'] = this.s30;
    data['31'] = this.s31;
    data['32'] = this.s32;
    data['33'] = this.s33;
    data['34'] = this.s34;
    data['35'] = this.s35;
    data['36'] = this.s36;
    data['37'] = this.s37;
    data['38'] = this.s38;
    data['39'] = this.s39;
    data['40'] = this.s40;
    data['41'] = this.s41;
    data['42'] = this.s42;
    data['43'] = this.s43;
    data['44'] = this.s44;
    data['45'] = this.s45;
    data['46'] = this.s46;
    data['47'] = this.s47;
    data['48'] = this.s48;
    data['49'] = this.s49;
    data['50'] = this.s50;
    data['51'] = this.s51;
    data['52'] = this.s52;
    data['53'] = this.s53;
    data['54'] = this.s54;
    data['55'] = this.s55;
    data['56'] = this.s56;
    data['57'] = this.s57;
    data['58'] = this.s58;
    data['59'] = this.s59;
    data['60'] = this.s60;
    data['61'] = this.s61;
    data['62'] = this.s62;
    data['63'] = this.s63;
    data['64'] = this.s64;
    data['65'] = this.s65;
    data['66'] = this.s66;
    data['67'] = this.s67;
    data['68'] = this.s68;
    data['69'] = this.s69;
    data['70'] = this.s70;
    data['71'] = this.s71;
    data['72'] = this.s72;
    data['73'] = this.s73;
    data['74'] = this.s74;
    data['75'] = this.s75;
    data['76'] = this.s76;
    data['77'] = this.s77;
    data['78'] = this.s78;
    data['79'] = this.s79;
    data['80'] = this.s80;
    data['81'] = this.s81;
    data['82'] = this.s82;
    data['83'] = this.s83;
    data['84'] = this.s84;
    data['85'] = this.s85;
    data['86'] = this.s86;
    data['87'] = this.s87;
    data['88'] = this.s88;
    data['89'] = this.s89;
    data['90'] = this.s90;
    data['91'] = this.s91;
    data['92'] = this.s92;
    data['93'] = this.s93;
    data['94'] = this.s94;
    data['95'] = this.s95;
    data['96'] = this.s96;
    data['97'] = this.s97;
    data['98'] = this.s98;
    data['99'] = this.s99;
    data['100'] = this.s100;
    data['101'] = this.s101;
    data['102'] = this.s102;
    data['103'] = this.s103;
    data['104'] = this.s104;
    data['105'] = this.s105;
    data['106'] = this.s106;
    data['107'] = this.s107;
    data['108'] = this.s108;
    data['109'] = this.s109;
    data['110'] = this.s110;
    data['111'] = this.s111;
    data['112'] = this.s112;
    data['113'] = this.s113;
    data['114'] = this.s114;
    data['115'] = this.s115;
    data['116'] = this.s116;
    data['117'] = this.s117;
    data['118'] = this.s118;
    data['119'] = this.s119;
    data['120'] = this.s120;
    data['121'] = this.s121;
    data['122'] = this.s122;
    data['123'] = this.s123;
    data['124'] = this.s124;
    data['125'] = this.s125;
    data['126'] = this.s126;
    data['127'] = this.s127;
    data['128'] = this.s128;
    data['129'] = this.s129;
    data['130'] = this.s130;
    data['131'] = this.s131;
    data['132'] = this.s132;
    data['133'] = this.s133;
    data['134'] = this.s134;
    data['135'] = this.s135;
    return data;
  }
}

class LanguagesProficiencies {
  String? s1;
  String? s2;
  String? s3;
  String? s4;
  String? s5;
  String? s6;

  LanguagesProficiencies(
      {this.s1, this.s2, this.s3, this.s4, this.s5, this.s6});

  LanguagesProficiencies.fromJson(Map<String, dynamic> json) {
    s1 = json['1'] as String?;
    s2 = json['2'] as String?;
    s3 = json['3'] as String?;
    s4 = json['4'] as String?;
    s5 = json['5'] as String?;
    s6 = json['6'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1'] = this.s1;
    data['2'] = this.s2;
    data['3'] = this.s3;
    data['4'] = this.s4;
    data['5'] = this.s5;
    data['6'] = this.s6;
    return data;
  }
}

class UserTitleTypes {
  String? s1;
  String? s2;
  String? s3;
  String? s4;
  String? s5;
  String? s6;
  String? s7;
  String? s8;
  String? s9;
  String? s10;
  String? s11;

  UserTitleTypes(
      {this.s1,
      this.s2,
      this.s3,
      this.s4,
      this.s5,
      this.s6,
      this.s7,
      this.s8,
      this.s9,
      this.s10,
      this.s11});

  UserTitleTypes.fromJson(Map<String, dynamic> json) {
    s1 = json['1'] as String?;
    s2 = json['2'] as String?;
    s3 = json['3'] as String?;
    s4 = json['4'] as String?;
    s5 = json['5'] as String?;
    s6 = json['6'] as String?;
    s7 = json['7'] as String?;
    s8 = json['8'] as String?;
    s9 = json['9'] as String?;
    s10 = json['10'] as String?;
    s11 = json['11'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1'] = this.s1;
    data['2'] = this.s2;
    data['3'] = this.s3;
    data['4'] = this.s4;
    data['5'] = this.s5;
    data['6'] = this.s6;
    data['7'] = this.s7;
    data['8'] = this.s8;
    data['9'] = this.s9;
    data['10'] = this.s10;
    data['11'] = this.s11;
    return data;
  }
}

class ExpertiseList {
  String? s71;
  String? s72;

  ExpertiseList({this.s71, this.s72});

  ExpertiseList.fromJson(Map<String, dynamic> json) {
    s71 = json['71'] as String?;
    s72 = json['72'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['71'] = this.s71;
    data['72'] = this.s72;
    return data;
  }
}

// class Settings {
//   HeaderLinks headerLinks;
//   GeneralSettings generalSettings;

//   Settings({this.headerLinks, this.generalSettings});

//   Settings.fromJson(Map<String, dynamic> json) {
//     headerLinks = json['HeaderLinks'] != null
//         ? new HeaderLinks.fromJson(json['HeaderLinks'])
//         : null;
//     generalSettings = json['GeneralSettings'] != null
//         ? new GeneralSettings.fromJson(json['GeneralSettings'])
//         : null;
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['HeaderLinks'] = this.headerLinks.toJson();
//     data['GeneralSettings'] = this.generalSettings.toJson();
//     return data;
//   }
// }

class HeaderLinks {
  String? holedoHub;
  String? holedoChat;
  String? holedoJobs;

  HeaderLinks({this.holedoHub, this.holedoChat, this.holedoJobs});

  HeaderLinks.fromJson(Map<String, dynamic> json) {
    holedoHub = json['Holedo Hub'] as String?;
    holedoChat = json['Holedo Chat'] as String?;
    holedoJobs = json['Holedo Jobs'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Holedo Hub'] = this.holedoHub;
    data['Holedo Chat'] = this.holedoChat;
    data['Holedo Jobs'] = this.holedoJobs;
    return data;
  }
}

class GeneralSettings {
  String? facebookFollowers;
  String? youtubeSubscribers;
  String? twitterFollowers;
  String? instagramFollowers;
  String? googleplusFollowers;
  String? pinterestFollowers;
  String? linkedinFollowers;
  String? jobCardBannerFallback;
  String? jobCardBannerFallbackAlternate;
  String? logoFallback;
  String? companyBannerFallback;
  String? companyBannerFallbackAlternate;
  String? codeHeaderEnabled;
  String? codeHeaderHtml;
  String? codeBodyEnabled;
  String? codeBodyHtml;
  String? codePostTopEnabled;
  String? codePostTopHtml;
  String? codePostBottomEnabled;
  String? codePostBottomHtml;

  GeneralSettings(
      {this.facebookFollowers,
      this.youtubeSubscribers,
      this.twitterFollowers,
      this.instagramFollowers,
      this.googleplusFollowers,
      this.pinterestFollowers,
      this.linkedinFollowers,
      this.jobCardBannerFallback,
      this.jobCardBannerFallbackAlternate,
      this.logoFallback,
      this.companyBannerFallback,
      this.companyBannerFallbackAlternate,
      this.codeHeaderEnabled,
      this.codeHeaderHtml,
      this.codeBodyEnabled,
      this.codeBodyHtml,
      this.codePostTopEnabled,
      this.codePostTopHtml,
      this.codePostBottomEnabled,
      this.codePostBottomHtml});

  GeneralSettings.fromJson(Map<String, dynamic> json) {
    facebookFollowers = json['facebook_followers'] as String?;
    youtubeSubscribers = json['youtube_subscribers'] as String?;
    twitterFollowers = json['twitter_followers'] as String?;
    instagramFollowers = json['instagram_followers'] as String?;
    googleplusFollowers = json['googleplus_followers'] as String?;
    pinterestFollowers = json['pinterest_followers'] as String?;
    linkedinFollowers = json['linkedin_followers'] as String?;
    jobCardBannerFallback = json['job_card_banner_fallback'] as String?;
    jobCardBannerFallbackAlternate =
        json['job_card_banner_fallback_alternate'] as String?;
    logoFallback = json['logo_fallback'] as String?;
    companyBannerFallback = json['company_banner_fallback'] as String?;
    companyBannerFallbackAlternate =
        json['company_banner_fallback_alternate'] as String?;
    codeHeaderEnabled = json['code_header_enabled'] as String?;
    codeHeaderHtml = json['code_header_html'] as String?;
    codeBodyEnabled = json['code_body_enabled'] as String?;
    codeBodyHtml = json['code_body_html'] as String?;
    codePostTopEnabled = json['code_post_top_enabled'] as String?;
    codePostTopHtml = json['code_post_top_html'] as String?;
    codePostBottomEnabled = json['code_post_bottom_enabled'] as String?;
    codePostBottomHtml = json['code_post_bottom_html'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['facebook_followers'] = this.facebookFollowers;
    data['youtube_subscribers'] = this.youtubeSubscribers;
    data['twitter_followers'] = this.twitterFollowers;
    data['instagram_followers'] = this.instagramFollowers;
    data['googleplus_followers'] = this.googleplusFollowers;
    data['pinterest_followers'] = this.pinterestFollowers;
    data['linkedin_followers'] = this.linkedinFollowers;
    data['job_card_banner_fallback'] = this.jobCardBannerFallback;
    data['job_card_banner_fallback_alternate'] =
        this.jobCardBannerFallbackAlternate;
    data['logo_fallback'] = this.logoFallback;
    data['company_banner_fallback'] = this.companyBannerFallback;
    data['company_banner_fallback_alternate'] =
        this.companyBannerFallbackAlternate;
    data['code_header_enabled'] = this.codeHeaderEnabled;
    data['code_header_html'] = this.codeHeaderHtml;
    data['code_body_enabled'] = this.codeBodyEnabled;
    data['code_body_html'] = this.codeBodyHtml;
    data['code_post_top_enabled'] = this.codePostTopEnabled;
    data['code_post_top_html'] = this.codePostTopHtml;
    data['code_post_bottom_enabled'] = this.codePostBottomEnabled;
    data['code_post_bottom_html'] = this.codePostBottomHtml;
    return data;
  }
}

class Block {
  Headline? headline;
  CategoryTypeA? categoryTypeA;
  CategoryTypeB? categoryTypeB;
  Video? video;
  Video? category;
  Video? widgetTypeA;
  Video? widgetTypeB;
  Video? widgetTypeC;
  Video? widgetTypeD;
  Video? widgetTypeE;

  Block(
      {this.headline,
      this.categoryTypeA,
      this.categoryTypeB,
      this.video,
      this.category,
      this.widgetTypeA,
      this.widgetTypeB,
      this.widgetTypeC,
      this.widgetTypeD,
      this.widgetTypeE});

  Block.fromJson(Map<String, dynamic> json) {
    if (json['headline'] != null) {
      headline =
          new Headline.fromJson(json['headline'] as Map<String, dynamic>);
    } else {
      headline = null;
    }
    if (json['category_type_a'] != null) {
      categoryTypeA = new CategoryTypeA.fromJson(
          json['category_type_a'] as Map<String, dynamic>);
    } else {
      categoryTypeA = null;
    }
    categoryTypeB = json['category_type_b'] != null
        ? new CategoryTypeB.fromJson(
            json['category_type_b'] as Map<String, dynamic>)
        : null;
    video = json['video'] != null
        ? new Video.fromJson(json['video'] as Map<String, dynamic>)
        : null;
    category = json['category'] != null
        ? new Video.fromJson(json['category'] as Map<String, dynamic>)
        : null;
    widgetTypeA = json['widget_type_a'] != null
        ? new Video.fromJson(json['widget_type_a'] as Map<String, dynamic>)
        : null;
    widgetTypeB = json['widget_type_b'] != null
        ? new Video.fromJson(json['widget_type_b'] as Map<String, dynamic>)
        : null;
    widgetTypeC = json['widget_type_c'] != null
        ? new Video.fromJson(json['widget_type_c'] as Map<String, dynamic>)
        : null;
    widgetTypeD = json['widget_type_d'] != null
        ? new Video.fromJson(json['widget_type_d'] as Map<String, dynamic>)
        : null;
    widgetTypeE = json['widget_type_e'] != null
        ? new Video.fromJson(json['widget_type_e'] as Map<String, dynamic>)
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['headline'] = this.headline!.toJson();
    data['category_type_a'] = this.categoryTypeA!.toJson();
    data['category_type_b'] = this.categoryTypeB!.toJson();
    data['video'] = this.video!.toJson();
    data['category'] = this.category!.toJson();
    data['widget_type_a'] = this.widgetTypeA!.toJson();
    data['widget_type_b'] = this.widgetTypeB!.toJson();
    data['widget_type_c'] = this.widgetTypeC!.toJson();
    data['widget_type_d'] = this.widgetTypeD!.toJson();
    data['widget_type_e'] = this.widgetTypeE!.toJson();
    return data;
  }
}

class Headline {
  String? widget;
  String? blockType;
  String? centerColumns;
  String? widgetLeft;
  String? widgetRight;
  String? widgetCenterLeft;
  String? widgetCenterRight;

  Headline(
      {this.widget,
      this.blockType,
      this.centerColumns,
      this.widgetLeft,
      this.widgetRight,
      this.widgetCenterLeft,
      this.widgetCenterRight});

  Headline.fromJson(Map<String, dynamic> json) {
    widget = json['Widget'] as String?;
    blockType = json['block_type'] as String?;
    centerColumns = json['center_columns'] as String?;
    widgetLeft = json['widget_left'] as String?;
    widgetRight = json['widget_right'] as String?;
    widgetCenterLeft = json['widget_center_left'] as String?;
    widgetCenterRight = json['widget_center_right'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Widget'] = this.widget;
    data['block_type'] = this.blockType;
    data['center_columns'] = this.centerColumns;
    data['widget_left'] = this.widgetLeft;
    data['widget_right'] = this.widgetRight;
    data['widget_center_left'] = this.widgetCenterLeft;
    data['widget_center_right'] = this.widgetCenterRight;
    return data;
  }
}

class CategoryTypeA {
  String? widgets;
  String? widgetCenterRight;
  String? widgetCenterLeft;
  String? widgetRight;
  String? widgetLeft;
  String? centerColumns;
  String? blockType;

  CategoryTypeA(
      {this.widgets,
      this.widgetCenterRight,
      this.widgetCenterLeft,
      this.widgetRight,
      this.widgetLeft,
      this.centerColumns,
      this.blockType});

  CategoryTypeA.fromJson(Map<String, dynamic> json) {
    widgets = json['Widgets'] as String?;
    widgetCenterRight = json['widget_center_right'] as String?;
    widgetCenterLeft = json['widget_center_left'] as String?;
    widgetRight = json['widget_right'] as String?;
    widgetLeft = json['widget_left'] as String?;
    centerColumns = json['center_columns'] as String?;
    blockType = json['block_type'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Widgets'] = this.widgets;
    data['widget_center_right'] = this.widgetCenterRight;
    data['widget_center_left'] = this.widgetCenterLeft;
    data['widget_right'] = this.widgetRight;
    data['widget_left'] = this.widgetLeft;
    data['center_columns'] = this.centerColumns;
    data['block_type'] = this.blockType;
    return data;
  }
}

class CategoryTypeB {
  String? backgroundColor;
  String? headerColor;
  String? widgetCenterRight;
  String? widgetCenterLeft;
  String? widgetRight;
  String? widgetLeft;
  String? centerColumns;
  String? blockType;

  CategoryTypeB(
      {this.backgroundColor,
      this.headerColor,
      this.widgetCenterRight,
      this.widgetCenterLeft,
      this.widgetRight,
      this.widgetLeft,
      this.centerColumns,
      this.blockType});

  CategoryTypeB.fromJson(Map<String, dynamic> json) {
    backgroundColor = json['background_color'] as String?;
    headerColor = json['header_color'] as String?;
    widgetCenterRight = json['widget_center_right'] as String?;
    widgetCenterLeft = json['widget_center_left'] as String?;
    widgetRight = json['widget_right'] as String?;
    widgetLeft = json['widget_left'] as String?;
    centerColumns = json['center_columns'] as String?;
    blockType = json['block_type'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['background_color'] = this.backgroundColor;
    data['header_color'] = this.headerColor;
    data['widget_center_right'] = this.widgetCenterRight;
    data['widget_center_left'] = this.widgetCenterLeft;
    data['widget_right'] = this.widgetRight;
    data['widget_left'] = this.widgetLeft;
    data['center_columns'] = this.centerColumns;
    data['block_type'] = this.blockType;
    return data;
  }
}

class Video {
  String? widgetCenterRight;
  String? widgetCenterLeft;
  String? widgetRight;
  String? widgetLeft;
  String? centerColumns;
  String? blockType;

  Video(
      {this.widgetCenterRight,
      this.widgetCenterLeft,
      this.widgetRight,
      this.widgetLeft,
      this.centerColumns,
      this.blockType});

  Video.fromJson(Map<String, dynamic> json) {
    widgetCenterRight = json['widget_center_right'] as String?;
    widgetCenterLeft = json['widget_center_left'] as String?;
    widgetRight = json['widget_right'] as String?;
    widgetLeft = json['widget_left'] as String?;
    centerColumns = json['center_columns'] as String?;
    blockType = json['block_type'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['widget_center_right'] = this.widgetCenterRight;
    data['widget_center_left'] = this.widgetCenterLeft;
    data['widget_right'] = this.widgetRight;
    data['widget_left'] = this.widgetLeft;
    data['center_columns'] = this.centerColumns;
    data['block_type'] = this.blockType;
    return data;
  }
}

class ArticleCategories {
  int? id;
  dynamic parentId;
  String? slug;
  String? title;
  bool? menuItem;
  String? blockType;

  ArticleCategories(
      {this.id,
      this.parentId,
      this.slug,
      this.title,
      this.menuItem,
      this.blockType});

  ArticleCategories.fromJson(Map<String, dynamic> json) {
    id = json['id'] as int;
    parentId = json['parent_id'] as String?;
    slug = json['slug'] as String?;
    title = json['title'] as String?;
    menuItem = json['menu_item'] as bool?;
    blockType = json['block_type'] as String?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['parent_id'] = this.parentId;
    data['slug'] = this.slug;
    data['title'] = this.title;
    data['menu_item'] = this.menuItem;
    data['block_type'] = this.blockType;
    return data;
  }
}
